# Generated by Django 3.1.13 on 2022-12-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_team_memters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_memters',
            new_name='team_members',
        ),
    ]
