# Generated by Django 3.1.13 on 2022-12-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
