# Generated by Django 3.1.13 on 2022-12-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_auto_20221223_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
