# Generated by Django 3.1.13 on 2022-12-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_commission_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='work_id',
            new_name='parent_work',
        ),
    ]
