# Generated by Django 3.1.13 on 2022-12-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_commission_is_cancled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioncomment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Work description'),
        ),
    ]
