# Generated by Django 3.1.13 on 2022-12-30 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_commissionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
