# Generated by Django 3.1.13 on 2022-12-21 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timedate_created', models.DateTimeField(verbose_name='Work created')),
                ('date_due', models.DateField(verbose_name='Work due')),
                ('department_charge', models.IntegerField(verbose_name='department in charger')),
                ('description', models.CharField(max_length=255, verbose_name='Work description')),
                ('title', models.CharField(max_length=255, verbose_name='Work title')),
                ('datetime_completed', models.DateTimeField(verbose_name='completed datetime')),
                ('user_completed', models.IntegerField(blank=True, null=True, verbose_name='completed user')),
                ('workers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
