# Generated by Django 3.1.13 on 2022-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20221222_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='datetime_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='completed datetime'),
        ),
    ]
