# Generated by Django 3.1.13 on 2022-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20221222_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
