# Generated by Django 3.1.13 on 2022-12-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='department_charge',
            new_name='team_id',
        ),
    ]
