# Generated by Django 3.1.13 on 2022-12-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_auto_20221222_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='workers',
        ),
    ]
