# Generated by Django 3.1.13 on 2022-12-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20221222_2242'),
        ('works', '0007_remove_work_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
    ]
