# Generated by Django 3.1.13 on 2022-12-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0010_work_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='team_id',
            new_name='team',
        ),
    ]
