# Generated by Django 3.1.13 on 2022-12-24 09:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20221222_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_by',
            field=models.IntegerField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
