# Generated by Django 3.1.13 on 2022-12-26 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0014_auto_20221225_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Work description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.work')),
            ],
        ),
    ]
