# Generated by Django 3.1.13 on 2022-12-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0016_auto_20221230_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrokhistory',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='add, view, edit, cancle'),
        ),
    ]
