# Generated by Django 3.1.13 on 2022-12-30 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0017_auto_20221230_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wrokhistory',
            name='kind',
            field=models.CharField(max_length=100, verbose_name='add, view, edit, cancle, complete'),
        ),
    ]
